version: '2'
services:
    predicting-popularity:
        build: .
        ports:
            - "5000:5000"
        environment:
            - PORT=5000
            - SPOTIFY_CLIENT_ID=
            - SPOTIFY_CLIENT_SECRET=
        restart: unless-stopped
